---
# AWS tasks are run 'locally'

# Authentication details should be passed in as arguments or exported in the shell before running this playbook
# Ideally they should be stored in Hashicorp's 'Vault'
# e.g.
# export AWS_ACCESS_KEY_ID='my-access-key123'
# export AWS_SECRET_ACCESS_KEY='sekrit23418'
#
# Run with `ansible-playbook provision-aws-mattermost.yml`

- name: Provision EC2 and RDS infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create a basic web security group (TCP 22, 80, 443 IN)
      ec2_group:
        name: "{{ web_security_group_name }}"
        description: A basic web security group that allows 22, 80, and 443 inbound
        # Will be created in our default VPC, unless specified
        # vpc_id: 12345
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            from_port: all
            to_port: all
            cidr_ip: 0.0.0.0/0
      register: web_secgroup
       
    - name: Web Security Group
      debug: msg="{{ web_secgroup }}"

    - name: Create a basic database security group (TCP 5432 IN)
      ec2_group:
        name: "{{ db_security_group_name }}"
        description: A security group that allows database connections to postgres
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 5432
            to_port: 5432
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            from_port: all
            to_port: all
            #type: all
            cidr_ip: 0.0.0.0/0
      register: db_secgroup

    - name: DB Security Group
      debug: msg="{{ db_secgroup }}"
    
    # RDS instances only take security group *IDs,* and EC2 instances only take *names*
    # Sigh.
    - set_fact: db_security_group_id="{{ db_secgroup['group_id'] }}"


    - name: Provision a database instance
      rds:
        command: create
        db_name: "{{ database_name }}"
        instance_name: "{{ db_master_name }}"
        vpc_security_groups: "{{ db_security_group_id }}"
        db_engine: postgres
        size: 10
        instance_type: db.t2.micro
        region: "{{ aws_region }}"
        username: "{{ db_master_user }}"
        password: "{{ db_master_pass }}"
        tags:
          Environment: prod
          Application: mattermost
      register: rdsmachines

    # AWS is really slow
    - pause: prompt="Now you'll need to wait for 5-10 minutes for your RDS instance to come up, before quitting and re-running this Ansible playbook"
    
    # Check to make sure we've got the info we need from the RDS instance
    - debug: var=rdsmachines
    - set_fact: db_server="{{ rdsmachines['instance']['endpoint'] }}"
    
    # Write our RDS server's hostname into a file
    - name: Save our RDS servername to a local file.
      local_action: copy content={{ db_server }} dest=group_vars/rdsname
    
    - debug: var=db_server

    - name: Provision a read-only replica of our database instance
      rds:
        command: replicate
        instance_name: "{{ db_replica_name }}"
        region: "{{ aws_region }}"
        source_instance: "{{ db_master_name }}"

    - name: Provision a set of web instances
      ec2:
        region: "{{ aws_region }}"
        group: "{{ web_security_group_name }}"
        key_name: "{{ aws_pubkey_name }}"
        instance_type: t2.micro
        image: "{{ web_ami_id }}"
        wait: true
        exact_count: "{{ web_instance_count }}"
        count_tag:
          Name: Mattermost
        instance_tags:
          Name: mattermost-web
          Environment: prod
          Application: mattermost
      register: ec2
    
    - name: Add all web instance IPs to host group
      add_host: hostname={{ item.public_ip }} groupname=webservers
      with_items: '{{ ec2.instances }}'
    
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ ec2.instances }}'


##################################################################
# And now, the original playbook from the single-host version.
# We don't need the 'database' role, since an RDS instance is not 
# treated as a normal machine.
##################################################################

- hosts: webservers
  name: Webserver Setup
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  roles:
    - bootstrap
    - common
    - web

